_extends: .github:.github/_opensource.yml

repository:
  name: hover-align
  description: A basic FoundryVTT module to display PC/NPC alignment when hovering over a token
  topics: foundryvtt, dnd5e, alignment
  is_template: false
  delete_branch_on_merge: true
  has_issues: true
  has_projects: true
  has_downloads: true
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

labels:
  - name: dependencies
    color: '#70f9e0'
    description: Update dependencies

branches:
  - name: master
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        dismissal_restrictions: {}
      required_status_checks:
        strict: true
        contexts: ['Lint']
      required_signatures: true
      enforce_admins: null
      restrictions: null
