name: Build

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  read-node-version:
    name: Read Node.js version
    outputs:
      node-version: ${{ steps.node-version.outputs.NODE_VERSION }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Read .nvmrc
        id: node-version
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)

  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - read-node-version
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ needs.read-node-version.outputs.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ needs.read-node-version.outputs.node-version }}
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm install -g markdownlint-cli
      - run: markdownlint *.md
      - run: npm ci
      - run: npm run lint
      - run: npm run test:ci
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          flags: unittests
