name: Lint

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

env:
  NODE_VERSION: 14.13.1

jobs:
  lint:
    name: Lint Markdown files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm install -g markdownlint-cli
      - run: markdownlint *.md
